# Generated by Django 3.2.9 on 2021-11-12 19:16

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCommunicationRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('submitted_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='NewTerminalBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NTB_code', models.CharField(max_length=100)),
                ('NTB_number', models.IntegerField()),
                ('submitted_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='OldTerminalBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OTB_code', models.CharField(max_length=100)),
                ('OTB_name', models.CharField(max_length=100)),
                ('submitted_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='OtherBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=100)),
                ('submitted_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('AIB_number', models.CharField(max_length=100)),
                ('position_title', models.CharField(max_length=200)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('job_duties', models.TextField()),
                ('access_justification', models.TextField()),
                ('wap_roa', models.CharField(max_length=255)),
                ('required_access', models.CharField(choices=[('STANDARD', 'Standard'), ('TEMPORARY', 'Temporary')], max_length=200)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('other_locations', models.TextField()),
                ('specify_system_list', models.TextField(blank=True)),
                ('specify_equipment_list', models.TextField(blank=True)),
                ('specify_server_list', models.TextField(blank=True)),
                ('Specify_cables', models.TextField(blank=True)),
                ('agreed_to_terms', models.BooleanField()),
                ('submitted_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('building', models.ManyToManyField(to='FormPage.OtherBuilding')),
                ('main_communications_room', models.ManyToManyField(to='FormPage.MainCommunicationRoom')),
                ('new_terminal_building', models.ManyToManyField(to='FormPage.NewTerminalBuilding')),
                ('old_terminal_building', models.ManyToManyField(to='FormPage.OldTerminalBuilding')),
            ],
        ),
    ]
