# Generated by Django 3.2.9 on 2021-11-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormPage', '0002_alter_form_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='end_time',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='main_communications_room',
            field=models.ManyToManyField(blank=True, to='FormPage.MainCommunicationRoom'),
        ),
        migrations.AlterField(
            model_name='form',
            name='new_terminal_building',
            field=models.ManyToManyField(blank=True, to='FormPage.NewTerminalBuilding'),
        ),
        migrations.AlterField(
            model_name='form',
            name='old_terminal_building',
            field=models.ManyToManyField(blank=True, to='FormPage.OldTerminalBuilding'),
        ),
        migrations.AlterField(
            model_name='form',
            name='start_time',
            field=models.DateField(blank=True),
        ),
    ]
