# Generated by Django 3.2.9 on 2021-11-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormPage', '0003_auto_20211116_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='building',
            field=models.ManyToManyField(blank=True, to='FormPage.OtherBuilding'),
        ),
        migrations.AlterField(
            model_name='form',
            name='other_locations',
            field=models.TextField(blank=True),
        ),
    ]
