# Generated by Django 3.2.9 on 2021-11-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormPage', '0004_auto_20211117_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
