# Generated by Django 3.2.9 on 2021-11-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormPage', '0005_form_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='end_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='start_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
