# Generated by Django 3.2.9 on 2021-11-25 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FormPage', '0006_auto_20211119_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='files',
        ),
        migrations.CreateModel(
            name='FormFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='uploaded_files')),
                ('form_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FormPage.form')),
            ],
        ),
    ]
