# Generated by Django 3.2.9 on 2021-11-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormPage', '0008_alter_formfiles_form_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfiles',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_files'),
        ),
    ]
