# Generated by Django 3.2.9 on 2021-11-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormPage', '0009_alter_formfiles_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='agreed_to_terms',
            field=models.BooleanField(default=False),
        ),
    ]
