# Generated by Django 3.2.9 on 2021-11-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormPage', '0010_alter_form_agreed_to_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='agreed_to_terms',
            field=models.BooleanField(default=True),
        ),
    ]
