# Generated by Django 3.2.9 on 2022-01-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormPage', '0012_alter_form_agreed_to_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='approved_or_not',
            field=models.CharField(blank=True, choices=[('APPROVED', 'Approve'), ('REJECT', 'Reject')], max_length=200, null=True),
        ),
    ]
