# Generated by Django 4.0.1 on 2022-02-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormPage', '0013_form_approved_or_not'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='required_access',
            field=models.CharField(choices=[('PERMANENT', 'Permanent'), ('TEMPORARY', 'Temporary')], max_length=200),
        ),
    ]
