# Generated by Django 4.0.1 on 2022-02-09 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormPage', '0014_alter_form_required_access'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ('-company_name',)},
        ),
    ]
