# Generated by Django 4.0.1 on 2022-02-09 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormPage', '0015_alter_form_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ('-id',)},
        ),
    ]
