# Generated by Django 4.0.1 on 2022-03-10 13:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_desc', models.TextField()),
                ('static_ip_conf', models.CharField(max_length=50)),
                ('static_ip_addr', models.CharField(max_length=100)),
                ('internal_ip_config', models.CharField(max_length=100)),
                ('internal_ip_range', models.CharField(max_length=100)),
                ('additional_conf', models.TextField()),
                ('submitted_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_name', models.CharField(max_length=200)),
                ('switch_model', models.CharField(max_length=100)),
                ('configuration', models.TextField()),
                ('vlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitadevices.vlan')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number', models.IntegerField()),
                ('port_desc', models.TextField()),
                ('associate', models.CharField(max_length=200)),
                ('status', models.BooleanField()),
                ('submitted_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitadevices.switch')),
            ],
        ),
    ]
