# Generated by Django 4.0.6 on 2022-07-21 15:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CommmunicationRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commroomname', models.CharField(max_length=255)),
                ('building_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitadevices.building')),
            ],
        ),
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_port_number', models.IntegerField(default=0)),
                ('duplex', models.CharField(choices=[('HALF', 'half'), ('FULL', 'full'), ('AUTO', 'auto')], max_length=200)),
                ('voice_vlan_number', models.IntegerField(default=0)),
                ('phone_mac_address', models.CharField(max_length=200)),
                ('phone_extension', models.CharField(max_length=200)),
                ('purpose', models.TextField()),
                ('sticky_port', models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], max_length=200)),
                ('additional_configuration', models.TextField()),
                ('remark', models.TextField()),
                ('actual_user', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('ACTIVE', 'active'), ('DISABLED', 'disabled')], max_length=200)),
                ('connection_date', models.DateField(default=django.utils.timezone.now)),
                ('disconnection_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('active', models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], max_length=200)),
                ('submitted_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerVlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_number', models.IntegerField()),
                ('usage', models.CharField(choices=[('ACCESS', 'access'), ('VOICE', 'voice')], max_length=200)),
                ('config_date', models.DateTimeField()),
                ('vlan_description', models.TextField()),
                ('ip_config', models.CharField(choices=[('STATIC', 'static'), ('DHCP', 'dhcp')], max_length=200)),
                ('dhcp_ip_range', models.CharField(max_length=50)),
                ('lan_ip_range', models.CharField(max_length=50)),
                ('lan_subnet_mask', models.CharField(max_length=50)),
                ('wan_public_ip', models.CharField(max_length=50)),
                ('wan_subnet_mask', models.CharField(max_length=50)),
                ('bandwidth', models.IntegerField()),
                ('additional_config', models.TextField()),
                ('remark', models.TextField()),
                ('disconnection_date', models.DateField(blank=True, null=True)),
                ('submitted_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('customor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitadevices.customer')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('request_date', models.DateField(default=django.utils.timezone.now)),
                ('service_desk_ticket_number', models.CharField(max_length=200)),
                ('request_type', models.CharField(choices=[('CONFIGURE', 'configure'), ('MODIFY', 'modify'), ('DISCONNECT', 'disconnect'), ('RESET', 'reset')], max_length=200)),
                ('request_description', models.TextField()),
                ('configuration_remark', models.TextField()),
                ('comment', models.TextField()),
                ('engineer_assigned', models.CharField(max_length=200)),
                ('submitted_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitadevices.customer')),
                ('connections', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitadevices.connections')),
                ('vlan_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitadevices.customervlan')),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_name', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('port_capacity', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('supplier', models.CharField(max_length=200)),
                ('poe_enabled', models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], max_length=200)),
                ('rack_number', models.CharField(max_length=200)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('ACTIVE', 'active'), ('DISABLED', 'disabled')], max_length=200)),
                ('communication_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitadevices.commmunicationroom')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=255)),
                ('building_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitadevices.building')),
            ],
        ),
        migrations.CreateModel(
            name='DataOutlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patch_panel', models.IntegerField()),
                ('port_status', models.CharField(choices=[('ACTIVE', 'active'), ('DISABLED', 'disabled')], max_length=200)),
                ('comroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitadevices.commmunicationroom')),
                ('office_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitadevices.room')),
            ],
        ),
        migrations.AddField(
            model_name='connections',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitadevices.customer'),
        ),
        migrations.AddField(
            model_name='connections',
            name='customerVlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitadevices.customervlan'),
        ),
        migrations.AddField(
            model_name='connections',
            name='data_outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitadevices.dataoutlet'),
        ),
    ]
