# Generated by Django 4.0.1 on 2022-03-10 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitadevices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='vlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitadevices.vlan'),
        ),
    ]
