# Generated by Django 4.0.6 on 2022-07-21 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitadevices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connections',
            name='data_outlet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitadevices.dataoutlet'),
        ),
    ]
