# Generated by Django 4.0.1 on 2022-03-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitadevices', '0002_alter_switch_vlan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('active', models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='switch',
            name='vlan',
        ),
        migrations.DeleteModel(
            name='Port',
        ),
        migrations.DeleteModel(
            name='Switch',
        ),
        migrations.DeleteModel(
            name='Vlan',
        ),
    ]
