# Generated by Django 4.0.1 on 2022-03-29 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitadevices', '0004_customer_submitted_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerVlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_number', models.IntegerField()),
                ('usage', models.CharField(choices=[('ACCESS', 'access'), ('VOICE', 'voice')], max_length=200)),
                ('config_date', models.DateTimeField()),
                ('vlan_description', models.TextField()),
                ('ip_config', models.CharField(choices=[('STATIC', 'static'), ('DHCP', 'dhcp')], max_length=200)),
                ('dhcp_ip_range', models.CharField(max_length=50)),
                ('lan_ip_range', models.CharField(max_length=50)),
                ('lan_subnet_mask', models.CharField(max_length=50)),
                ('wan_public_ip', models.CharField(max_length=50)),
                ('wan_subnet_mask', models.CharField(max_length=50)),
                ('bandwidth', models.IntegerField()),
                ('additional_config', models.TextField()),
                ('remark', models.TextField()),
                ('disconnection_date', models.DateField()),
                ('custumor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitadevices.customer')),
            ],
        ),
    ]
