# Generated by Django 4.0.1 on 2022-03-29 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitadevices', '0005_customervlan'),
    ]

    operations = [
        migrations.AddField(
            model_name='customervlan',
            name='submitted_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
