# Generated by Django 4.0.1 on 2022-03-30 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitadevices', '0006_customervlan_submitted_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitadevices.customer')),
                ('vlan_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitadevices.customervlan')),
            ],
        ),
    ]
