# Generated by Django 4.0.1 on 2022-03-30 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitadevices', '0007_workorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='submitted_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
