# Generated by Django 4.0.1 on 2022-03-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitadevices', '0008_workorder_submitted_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customervlan',
            name='disconnection_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
