# Generated by Django 4.0.1 on 2022-03-31 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitadevices', '0009_alter_customervlan_disconnection_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=255)),
                ('building_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitadevices.building')),
            ],
        ),
        migrations.CreateModel(
            name='CommmunicationRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commroomname', models.CharField(max_length=255)),
                ('building_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitadevices.building')),
            ],
        ),
    ]
