# Generated by Django 4.0.1 on 2022-04-04 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitadevices', '0010_building_room_commmunicationroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitadevices.customer')),
                ('customerVlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitadevices.customervlan')),
            ],
        ),
    ]
