# Generated by Django 4.0.1 on 2022-04-04 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitadevices', '0011_connections'),
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comms_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitadevices.commmunicationroom')),
            ],
        ),
    ]
