# Generated by Django 4.0.1 on 2022-04-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitadevices', '0013_dataoutlet'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataoutlet',
            name='data_number',
            field=models.CharField(default='', max_length=200),
        ),
    ]
