# Generated by Django 4.0.4 on 2022-04-21 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitadevices', '0015_alter_dataoutlet_data_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='connections',
            name='actual_user',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='connections',
            name='additional_configuration',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='connections',
            name='connection_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='connections',
            name='disconnection_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='connections',
            name='duplex',
            field=models.CharField(choices=[('HALF', 'half'), ('FULL', 'full'), ('AUTO', 'auto')], default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='connections',
            name='phone_extension',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='connections',
            name='phone_mac_address',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='connections',
            name='purpose',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='connections',
            name='remark',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='connections',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('DISABLED', 'disabled')], default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='connections',
            name='sticky_port',
            field=models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='connections',
            name='switch_port_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='connections',
            name='voice_vlan_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='switch',
            name='brand',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='switch',
            name='model',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='switch',
            name='owner',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='switch',
            name='poe_enabled',
            field=models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='switch',
            name='port_capacity',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='switch',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='switch',
            name='rach_number',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='switch',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('DISABLED', 'disabled')], default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='switch',
            name='supplier',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='switch',
            name='switch_name',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='workorder',
            name='comment',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='configuration_remark',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='engineer_assigned',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='workorder',
            name='request_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workorder',
            name='request_description',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='request_type',
            field=models.CharField(choices=[('CONFIGURE', 'configure'), ('MODIFY', 'modify'), ('DISCONNECT', 'disconnect'), ('RESET', 'reset')], default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='workorder',
            name='service_desk_ticket_number',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='workorder',
            name='work_order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dataoutlet',
            name='port_status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('DISABLED', 'disabled')], max_length=200),
        ),
    ]
