# Generated by Django 4.0.4 on 2022-04-30 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitadevices', '0016_connections_actual_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customervlan',
            old_name='custumor',
            new_name='customor',
        ),
        migrations.RenameField(
            model_name='switch',
            old_name='comms_room',
            new_name='communication_room',
        ),
        migrations.RenameField(
            model_name='switch',
            old_name='rach_number',
            new_name='rack_number',
        ),
    ]
