# Generated by Django 4.0.4 on 2022-05-03 14:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitadevices', '0017_rename_custumor_customervlan_customor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='connections',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='sitadevices.connections'),
            preserve_default=False,
        ),
    ]
